@echo off
del c:\windows\downlo~1\ABN*.*
del c:\windows\downlo~1\*ABN*.*
del c:\windows\downlo~1\GBPDIST.DLL
del c:\windows\downlo~1\scp*.*
del c:\windows\downlo~1\gb*.*
del c:\windows\downlo~1\*gb*.*
del c:\windows\downlo~1\*UNI*.*
del c:\windows\downlo~1\UNI*.*??
del C:\WINDOWS\system32\Logof.dll
del c:\arquiv~1\GbPlugin\gb*.*
del c:\arquiv~1\GbPlugin\g*.*
del c:\windwos\system32\snengine.exe
del c:\windwos\system32\snagos.exe
del c:\arquiv~1\Scpad\*scp*.??
del c:\arquiv~1\Scpad\scp*.*
del c:\windows\downlo~1\ATM*.*
del c:\windows\downlo~1\*ATM*.*
del c:\arquiv~1\Scpad\*ssh*.*
del c:\arquiv~1\Scpad\*ssh*.?
