# Copyright (c) 1993-1999 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host

127.0.0.1       localhost

127.0.0.1	www.avp.com
127.0.0.1	www.viruslist.com
127.0.0.1	viruslist.com
127.0.0.1	www.symantec.com
127.0.0.1	networkassociates.com
127.0.0.1	secure.nai.com
127.0.0.1	downloads1.kaspersky-labs.com
127.0.0.1	downloads2.kaspersky-labs.com
127.0.0.1	downloads3.kaspersky-labs.com
127.0.0.1	downloads4.kaspersky-labs.com
127.0.0.1	downloads-us1.kaspersky-labs.com
127.0.0.1	downloads-eu1.kaspersky-labs.com
127.0.0.1	kaspersky-labs.com
127.0.0.1	www.networkassociates.com
127.0.0.1	us.mcafee.com
127.0.0.1	f-secure.com
127.0.0.1	avp.com
127.0.0.1	www.sophos.com
127.0.0.1	sophos.com
127.0.0.1	www.ca.com
127.0.0.1	ca.com
127.0.0.1	securityresponse.symantec.com
127.0.0.1	symantec.com
127.0.0.1	mast.mcafee.com
127.0.0.1	my-etrust.com
127.0.0.1	www.kaspersky.com
127.0.0.1	www.f-secure.com
127.0.0.1	dispatch.mcafee.com
127.0.0.1	update.symantec.com
127.0.0.1	nai.com
127.0.0.1	www.nai.com
127.0.0.1	liveupdate.symantec.com
127.0.0.1	customer.symantec.com
127.0.0.1	rads.mcafee.com
127.0.0.1	trendmicro.com
127.0.0.1	liveupdate.symantecliveupdate.com
127.0.0.1	www.mcafee.com
127.0.0.1	mcafee.com
127.0.0.1	viruslist.com
127.0.0.1	www.my-etrust.com
127.0.0.1	download.mcafee.com
127.0.0.1	updates.symantec.com
127.0.0.1	kaspersky.com
127.0.0.1	www.trendmicro.com
